version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: openrouter-telegram-bot
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_PASSWORD=${BOT_PASSWORD}
      - TZ=UTC
    working_dir: /app
    # Configure log options
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"